version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocket-lms-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - rocket-network

  nginx:
    image: nginx:alpine
    container_name: rocket-lms-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - rocket-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: rocket-lms-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - rocket-db-data:/var/lib/mysql
    networks:
      - rocket-network

networks:
  rocket-network:
    driver: bridge

volumes:
  rocket-db-data:
    driver: local
